[project]
name = "crop-choice-ai"
version = "0.1.0"
description = "Crop Choice Intelligence System"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "flask",
    "scikit-learn",
    "pandas",
    "numpy",
    "joblib",
    "matplotlib",
    "seaborn"
]

[tool.vercel]
entrypoint = "flask_app.py"
